project:
  description: Log::Log4perl::Appender::AmazonSES
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm_module: Log::Log4perl::Appender::AmazonSES
min-perl-version: 5.010
dependencies:
  requires: requires
  test_requires: test-requires
path:
  pm_module: lib
  tests: t
extra-files:
  - README.md
  - share:
    - README.md
    - ChangeLog
resources:
  homepage: http://github.com/rlauer6/Log-Log4perl-Appender-AmazonSES
  bugtracker:
    web: http://github.com/rlauer6/Log-Log4perl-Appender-AmazonSES
    mailto: rclauer@gmail.com
  repository:
    url: git://github.com/rlauer6/Log-Log4perl-Appender-AmazonSES
    web: http://github.com/rlauer6/Log-Log4perl-Appender-AmazonSES
    type: 'git'
